name: jbr-linux-x64

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/lib/jvm/
        sudo -E apt-get update -y
        sudo -E apt-get install -y ant autoconf bison build-essential cmake flex git gperf ksh \
            libasound2-dev libavcodec-dev libavformat-dev libcups2-dev libfontconfig1-dev \
            libgl1-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libgtk2.0-dev libgtk-3-dev libjpeg-dev libpng-dev libudev-dev libx11-dev libxext-dev \
            libxml2-dev libxrandr-dev libxrender-dev libxslt1-dev libxt-dev libxtst-dev libxxf86vm-dev \
            make mercurial openjdk-11-jdk pkg-config ruby x11proto-core-dev x11proto-xf86vidmode-dev zip
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y

    - name: Prepare Source
      run: |
        git config --global core.autocrlf input
        hg clone http://hg.openjdk.java.net/openjfx/11-dev/rt
        git clone -b master --single-branch https://github.com/JetBrains/JetBrainsRuntime.git
        cd JetBrainsRuntime
        mv ../idea.patch ./
        patch -p1 < idea.patch

    - name: Compile OpenJFX
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        JDK_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      run: |
        cd rt
        chmod a+x gradlew
        ./gradlew -PCOMPILE_WEBKIT=true

    - name: Compile JetBrainsRuntime
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        JDK_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      run: |
        cd JetBrainsRuntime
        sh ./configure --disable-warnings-as-errors  --with-import-modules=../rt/build/modular-sdk
        make images

    - name: Collect Artifact
      run: |
        cd JetBrainsRuntime/build/linux-x86_64-normal-server-release/images
        mv jdk jbr
        zip -r jbr-linux-x64.zip ./jbr/*
        mv jbr-linux-x64.zip ../../../../

    - name: Assemble Artifact
      id: assemble_artifact
      env:
        TZ: Asia/Shanghai
      run: |
        time=$(date +%Y%m%d%H%M)
        release_tag=$time
        release_name="jbr-linux-x64-$time"
        echo "##[set-output name=release_name;]$release_name"
        echo "##[set-output name=release_tag;]$release_tag"

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.assemble_artifact.outputs.release_tag }}
        path: jbr-linux-x64.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
        release_name:  ${{ steps.assemble_artifact.outputs.release_name }}
        draft: false
        prerelease: true

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./jbr-linux-x64.zip
        asset_name: ${{ steps.assemble_artifact.outputs.release_name }}.zip
        asset_content_type: application/zip

